### Pobierz listę zadań
GET http://localhost:3001/tasks

### Dodaj nowe zadanie
POST http://localhost:3001/tasks
Content-Type: application/json

{
  "text": "Zrobić zakupy"
}

### Update zadania
PUT http://localhost:3001/tasks/1


### Usuń zadania
DELETE  http://localhost:3001/tasks/2


#### Rejestracja użytkownika
POST http://localhost:3001/auth/register
Content-Type: application/json

{
  "email": "Adrian",
  "password": "haslo123"
}

### Logowanie użytkownika
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "Adrian",
  "password": "haslo123"
}